---
Title: "UBCO Biology Undergraduate Resources"
pagetitle: "UBCO Biology Undergraduate Resources"
output:
  html_document:
    includes:
      in_header: header.html
---

```{r, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  warning = FALSE
)
```


```{r}
# read in the data
resources.biol <- read.csv("./files/resources.csv",
                           header = T)

# isolate lab manual content and order it
resources.labmanuals <- subset(resources.biol,
                               Type == "Lab-Manual",
                               select = c(Title, Link))
resources.labmanuals <- resources.labmanuals[ order(resources.labmanuals[,1]),]

# isolate non-lab manual resources
resources.resource <- subset(resources.biol,
                             Type == "Resource",
                             select = c(Title, Link))
```

## Lab Manuals & Tutorials

```{r, results='asis'}
# list and format the lab manuals

for (record in 1:nrow(resources.labmanuals)) {
  title <- resources.labmanuals[record,1]
  link <- resources.labmanuals[record,2]
  
  cat('<a href="',link,'" target="_blank"><div class="labManual resource">',title,'</div></a>')
}
```

<br /><br />

## Other Resources

```{r, results='asis'}
# list and format the other resources

for (record in 1:nrow(resources.resource)) {
  title <- resources.resource[record,1]
  link <- resources.resource[record,2]
  
  cat('<a href="',link,'" target="_blank"><div class="otherResource resource">',title,'</div></a>')
}
```